# Generated by Django 4.2.2 on 2023-06-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_carrito_total_alter_itemcarrito_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10),
        ),
    ]
