# Generated by Django 4.2.2 on 2023-06-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_carrito_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
