# Generated by Django 4.2.2 on 2023-06-30 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_itemcarrito_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=0, max_digits=5)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='user',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
        migrations.AddField(
            model_name='carrito',
            name='lineas',
            field=models.ManyToManyField(to='api.lineacarrito'),
        ),
    ]
