# Generated by Django 4.2.2 on 2023-06-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cart_cartitem_remove_lineacarrito_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
